### ISSUE TITLE
Customer details form's Mobile no. field should have a validation that number of digits should be 10

### ISSUE THREAD

**Issue by kbindra** [WooTechnology/DINE-IN#16]
**Description**
Customer details form in Front end folder has a Mobile no. field which doesn't have a validation yet that number should be a Ten digit number and it allows any number entered to get submitted to the database.

**Propsosal**
Add the above mentioned validation in class _Customerform's_ 
**validate** = ( ) => { 
...add a condition here to validate Mobile no....
}  
at Hotel app/frontend/src/components/Customer_details.js file.

**Example Screenshot**
![Screenshot from 2020-01-18 12-11-15](https://user-images.githubusercontent.com/51823406/72659862-12481380-39ec-11ea-8ab4-d8b056211566.png)

**Comment by Nancy-Chauhan** [comment]
It looks awesome . very nice description @kbindra
